// <auto-generated />
using System;
using EcoColeta.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoColeta.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoColeta.Api.Models.ColetaResiduo", b =>
                {
                    b.Property<int>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColeta"));

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPontoColeta")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoResiduo")
                        .HasColumnType("int");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.HasKey("IdColeta");

                    b.HasIndex("IdPontoColeta");

                    b.HasIndex("IdTipoResiduo");

                    b.ToTable("ColetasResiduos");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.PontoColeta", b =>
                {
                    b.Property<int>("IdPontoColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPontoColeta"));

                    b.Property<double>("CapacidadeMaxima")
                        .HasColumnType("float");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomePonto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusPonto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPontoColeta");

                    b.ToTable("PontosColeta");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.TipoResiduo", b =>
                {
                    b.Property<int>("IdTipoResiduo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoResiduo"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Reciclavel")
                        .HasColumnType("bit");

                    b.HasKey("IdTipoResiduo");

                    b.ToTable("TiposResiduos");
                });

            modelBuilder.Entity("EcoColeta.Api.Models.ColetaResiduo", b =>
                {
                    b.HasOne("EcoColeta.Api.Models.PontoColeta", "PontoColeta")
                        .WithMany()
                        .HasForeignKey("IdPontoColeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoColeta.Api.Models.TipoResiduo", "TipoResiduo")
                        .WithMany()
                        .HasForeignKey("IdTipoResiduo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");

                    b.Navigation("TipoResiduo");
                });
#pragma warning restore 612, 618
        }
    }
}
